### ISSUE TITLE
The graphs need some retouches

### ISSUE THREAD

**Issue by lu-zero** [giovannitangredi/wcc-analysis#2]
- [ ] The resolutions are completely off: the text is tiny compared to the bars or the bars are just way too big.
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/239012/174294001-2a36e66d-2d79-439b-a6e7-5a3703da433b.png">
- [ ] The graphs can show the `ratio` between the total files and the complex files, on the y axis you put the percentage so all the bars are at the same level (100%) and it is easy to see if the project is getting more complex over time.

I'm looking forward to see the analysis on functions, you may also plot them weighted by their loc.

**Comment by giovannitangredi** [comment]
FIxed resolution and bar size
Now the graph show the ratio as requested
